### ISSUE TITLE
General Writing Feedback

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/phase-3-running-python-code#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195259?module_item_id=439005

### Concern

In the **Installing pytest** section, we tell students to run `pipenv shell` to start working. We don't, however, tell them that we need this specifically to run the `pytest` command, which makes the purpose of `pipenv shell` ambiguous. We also don't tell them how to exit the `pipenv shell` (I experimented with it and found I could exit by typing `exit` into my terminal). We can pretty easily remedy this ambiguity by telling the we need to run `pipenv shell` in order to run `pytest` and that when we're done working we can type exit in our command line to exit the shell session. 

This may seem like a small issue, but even small lapses in clarity can consistently trip up students and create drag on their learning inertia. I can see at least a few students per phase coming to me with concerns about not being able to run pytest in their terminal if we leave things in their current state.

 I do like that you've included some info on how to actually read the test files! Most students are at a total loss when it comes to deciphering test files, so any context is super helpful.

**Comment by professor-ben** [comment]
Thanks for the feedback, Matt! I mentioned this in a previous issue, but I totally agree that we need to be more specific in the instructions for labs. This will be something that we handle in all labs moving forward, and we'll circle back around to these early lessons toward the end of this build.
