### ISSUE TITLE
Questions About pipenv

### ISSUE THREAD

**Issue by bdenney** [learn-co-curriculum/phase-3-running-python-code#2]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/195259?module_item_id=439005

### Concern

I had a couple points of confusion around `pipenv`. Specifically:

- Do we need to exit it when the lab is complete? I assume yes but had to figure out how to do that (possible I missed this!)
- Do we need to do `pipenv install` and `pipenv shell` for each lab? I did, but the instructions didn't tell us to.

**Comment by professor-ben** [comment]
Hey Brandon,

These are great questions. A couple other instructors and TCs have raised the same concern- we're updating all labs to include more specific instructions on constructing and deconstructing virtual environments. We're hoping to have this reflected in all of the build 1 and build 2 labs in the next release.

For the time being, the workflow should be as follows:

1. `pipenv install`
2. `pipenv shell`
3. `pytest -x` to run tests until the first error
4. `exit` in the terminal to exit your virtual environment

-Ben
