### ISSUE TITLE
Mismatch between directions and files 

### ISSUE THREAD

**Issue by ddeleon267** [learn-co-curriculum/phase-3-running-python-code#3]
### Canvas Link

https://learning.flatironschool.com/courses/6258/assignments/231393?module_item_id=541440

### Concern

The directions in the **Creating a Python Application** section tell the student to create the app.py file in lib, but it's already included when they fork the lab.

### Suggested Changes

Remove the app.py file from the main branch, or alter the instructions so that the student doesn't need to add it themself.

**Comment by professor-ben** [comment]
Just pushed a fix- thanks!
