### ISSUE TITLE
Folder Name

### ISSUE THREAD

**Issue by QSissler** [learn-co-curriculum/phase-3-running-python-code#4]
### Canvas Link

https://learning.flatironschool.com/courses/6274/assignments/236223?module_item_id=554031

### Concern

It looks like the lib folder has been renamed to be the lib/testing folder but the start of the read me walks them through the steps as if the folder was just named lib. This can be confusing for students who are new to python and unsure how to make this adjustment independently.

### Suggested Changes

 I recommended renaming the folder back to just lib.

**Comment by professor-ben** [comment]
Hi Quinn,

I can understand the source of confusion here. We wanted students to create their module inside of `lib/`, but VSCode seems to be making it difficult to access `lib/` without also accessing the `testing/` directory within. We will add something to `lib/` to make it more easily accessible to students.

Thanks,
Ben

**Comment by pgill97** [comment]
Added a gitignore file in the `lib` directory for both main and solution to fix vscode hiding directory.
