### ISSUE TITLE
Unclear Directions

### ISSUE THREAD

**Issue by connork97** [learn-co-curriculum/phase-3-running-python-code#5]
### Canvas Link

https://learning.flatironschool.com/courses/6274/assignments/236223?module_item_id=554031

### Concern

The "Introduction" and "Creating a Python Application" sections are quite unclear regarding the process of setting up a Python application for the first time, and what files to target/create/alter.  While it states to "code along" it makes it seem as though we are supposed to be navigating through our terminal and its preexisting files and folders rather than forking and cloning to code within the folder provided in the Github repository.

### Additional Context

"Let's dive right in. To get started on any new Python application, the first thing we need is a file. Create a new file in the lib/ directory called app.py. In this file, add the following..."

There are several folders throughout the Linux Subsystem for Window called "lib", such as in "linux/Ubuntu/usr/lib" that appeared to myself and other students to be what we were supposed to be targeting for this lesson, as though we were making a basic file from scratch.  At no point before or after did the lesson state to fork and clone the repository to work on that directly.  In Phase 1 and 2 it was almost always stated whether we would be forking and cloning to code along, complete a lab, or even try things out on our own system without requiring a Github repository at all (such as when learning about debugging in the browser console during Phase 1). 

### Suggested Changes

A simple, explicit statement to fork and clone the Github repository and to work directly from that would save many students time and energy.  It's a brand new language, and more importantly a brand new environment as we have to much more heavily rely on the CLI, so for the first lessons in particular it would be greatly helpful not to make students assume where to follow the instructions in the lessons.

**Comment by professor-ben** [comment]
Hi Connor,

Thanks for the report! I made a few changes to this paragraph that I think should provide clarity for future students.

Thanks again,
Ben

**Comment by connork97** [comment]
Looks great!  Thanks Ben.
